#!/usr/bin/env bash
# 03-install-dashboard.sh
# Installs and configures the Wazuh dashboard.
# Run AFTER 02-install-indexer.sh, from the same working directory
# (needs the wazuh-certificates/ folder generated by that script).

set -euo pipefail

echo "==> Installing wazuh-dashboard"
sudo apt-get install -y wazuh-dashboard

echo "==> Deploying dashboard certificates"
sudo mkdir -p /etc/wazuh-dashboard/certs
sudo cp wazuh-certificates/dashboard.pem /etc/wazuh-dashboard/certs/
sudo cp wazuh-certificates/dashboard-key.pem /etc/wazuh-dashboard/certs/
sudo cp wazuh-certificates/root-ca.pem /etc/wazuh-dashboard/certs/

sudo chmod 500 /etc/wazuh-dashboard/certs
sudo bash -c 'chmod 400 /etc/wazuh-dashboard/certs/*'
sudo chown -R wazuh-dashboard:wazuh-dashboard /etc/wazuh-dashboard/certs

echo "==> Setting indexer service-account credentials in dashboard config"
sudo sed -i 's/#opensearch.username:/opensearch.username: kibanaserver/' /etc/wazuh-dashboard/opensearch_dashboards.yml
sudo sed -i 's/#opensearch.password:/opensearch.password: kibanaserver/' /etc/wazuh-dashboard/opensearch_dashboards.yml

echo "==> Starting wazuh-dashboard"
sudo systemctl daemon-reload
sudo systemctl enable wazuh-dashboard
sudo systemctl start wazuh-dashboard

echo "==> Status (allow 30-90s for the dashboard's Node.js process to fully initialize):"
sudo systemctl status wazuh-dashboard --no-pager

echo "==> Browse to https://<this-host-ip>/ to access the dashboard (default login admin/admin)"
